# src/planning/schemas.py
"""
Pydantic schemas and dataclasses for Phase 3.3 Intent-Aware Retrieval Planning Layer.
Defines LegalQuestionIntent enum, classification result, retrieval plan, and execution trace.
"""

from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class LegalQuestionIntent(str, Enum):
    """Supported legal question intent types (§4)."""
    STATUTORY_INFORMATION = "statutory_information"
    CASE_LAW = "case_law"
    LEGAL_INTERPRETATION = "legal_interpretation"
    PROCEDURE = "procedure"
    MIXED = "mixed"
    CLARIFICATION_REQUIRED = "clarification_required"


class IntentClassificationResult(BaseModel):
    """Output of IntentClassifier."""
    intent: LegalQuestionIntent
    domain_hint: Optional[str] = Field(default=None, description="Inferred legal domain e.g., Consumer Protection, Criminal Law")
    jurisdiction_hint: Optional[str] = Field(default=None, description="central_only | state_specific | jurisdiction_ambiguous | None")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Classifier self-reported confidence score")
    reasoning: Optional[str] = Field(default=None, description="Brief explanation of intent assignment")


class RetrievalPlan(BaseModel):
    """Execution plan generated by RetrievalPlanner for retriever routing."""
    intent: LegalQuestionIntent
    source_mix: Dict[str, float] = Field(
        default_factory=lambda: {"legislation": 0.5, "judgment": 0.5},
        description="Target soft weighting between legislation and judgment candidates"
    )
    query_variants: List[str] = Field(default_factory=list, description="Optional phrasing variations for retrieval expansion")
    top_k_hints: Dict[str, int] = Field(default_factory=dict, description="Custom candidate_k or rerank_k hints per source")
    domain_filter: Optional[str] = Field(default=None, description="Domain tag filter if specified")
    jurisdiction_filter: Optional[str] = Field(default=None, description="Jurisdiction filter or soft-boost target")
    requires_clarification: bool = Field(default=False, description="True if query is too underspecified to retrieve")
    clarification_prompt: Optional[str] = Field(default=None, description="User-facing follow-up question if clarification is needed")


class PlanTrace(BaseModel):
    """Structured record attached to context for logging, debugging, and evaluation (§5)."""
    raw_query: str
    rewritten_query: str
    classified_intent: LegalQuestionIntent
    domain_hint: Optional[str] = None
    jurisdiction_hint: Optional[str] = None
    source_mix: Dict[str, float] = Field(default_factory=dict)
    fallback_triggered: bool = False
    fallback_reason: Optional[str] = None
    requires_clarification: bool = False
    latency_ms: float = 0.0
